on:
  push:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: ruby/setup-ruby@v1
    - name: Set up dependencies
      run: gem install nokogiri
    - name: Fetch latest data
      run: ruby firefly_guitars_for_sale.rb
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push

